# Generated by Django 3.1 on 2020-08-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200825_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_title',
            field=models.CharField(default='video_default_name', max_length=40),
            preserve_default=False,
        ),
    ]
